### PR TITLE
✨ [feat] Added `/unassignrole`; tiny, invisible changes & more

### PR DESCRIPTION
**Pull request by hitblast**
### Things changed:

- [x] Added a new `/unassignrole` slash command which can be used to remove a role from a given server member.
- [x] Both `/assignrole` and `unassignrole` now include member-based checks within them.
- [x] Parts of the music system's warnings are now ephemeral.
- [x] Tiny changes to the type hinting and command embeds have been made all over the codebase.
- [x] Reduced a small amount of repetitive code.

### CODE REVIEW

**Comment by hitblast** [comment]
@furtidev Would you like to have a look at this?

**Comment by furtidev** [comment]
> @furtidev Would you like to have a look at this?

It's a simple change though, just revert back to how it was before I guess.

**Comment by hitblast** [comment]
> > @furtidev Would you like to have a look at this?
> 
> It's a simple change though, just revert back to how it was before I guess.

Alright then I guess.

**Comment by hitblast** [comment]
@furtidev The change you mentioned which needed to be reverted, actually needs some fixes.

**Comment by hitblast** [comment]
> > @furtidev The change you mentioned which needed to be reverted, actually needs some fixes.
> 
> Oh, so what's up with it?

@furtidev See if a song fails to enqueue when we're attempting to put a playlist in, it'll still show the number of songs in the playlist instead of the total amount of enqueued (successfully) songs.

**Review by furtidev — APPROVED** [review]
Approving this for now then

**Pull request merged**
