### PR TITLE
A complete, basic music system; Migrate back to disnake and more!

### PR DESCRIPTION
**Pull request by hitblast**
### Things changed:
- [x] The music system of IgKnite is now complete with all the required commands for a smooth, first-stage experience.
- [x] Migrated the codebase back to [disnake](https://github.com/DisnakeDev/disnake), since it provides a better code pattern and plays well with our music cog as well (also it's *faster*).
- [x] Syntactic changes have been made, including new goodies like a better embed using `core.TypicalEmbed`!
- [x] Several new commands deriving from the `Inspection` cog thanks to @furtidev!
- [x] Fixed type hinting for optional parameters. For details, see: [PEP-484](https://peps.python.org/pep-0484/)
- [x] A better Guicer has been added to the kitchen (again thanks to @furtidev) :P
- [x] Updated the root-level markdown file.
... + more internal changes have been done.

### CODE REVIEW

**Review by furtidev — APPROVED** [review]
Alright, everything looks good to me :)

**Comment by hitblast** [comment]
Some separate testing could be needed before merging. @furtidev Thoughts?

**Review by furtidev — CHANGES_REQUESTED** [review]
### Issues so far:

- `/skip` doesn't work. **Error:** `'InteractionResponse' object has no attribute 'send'`
- Messages purged by IgKnite cannot be sniped. (Dunno if it's intentional or not.)
Other than that, everything else worked as expected.

**Comment by hitblast** [comment]
@furtidev 

1. It was indeed an error and was raised due to some bad code (`inter.reply()` and `inter.response.send()` were used instead of `inter.send()`).
2. It's not a bug, it's a feature :P

**Review by furtidev — APPROVED** [review]
Alright, looks good to me 🚀

**Pull request merged**
