### PR TITLE
Issue #59 Update Exception Handler

### PR DESCRIPTION
**Pull request by mpeiffer**
### Things changed:

- [x] Tested all commands for error outputs
- [x] Added exception handling for slash, command, and user errors
- [x] Updated title for exceptions

### Testing:
Using app command
permission err

### Note
Disnake seems to have a pretty comprehensive built in error handler, so I was only able to find missing role and permission errors. That said, there may be others that I couldn't find.

### CODE REVIEW

**Review by hitblast — CHANGES_REQUESTED** [review]
@mpeiffer Great work! By the way, one of the checks related to linting have failed. Just in case you don't know, we use [flake8](https://flake8.pycqa.org) for determining code style. Could you have a look at the failed check?

**Review by hitblast — APPROVED** [review]
I'll approve this change and work on the linter fixes in the `develop` branch since we need this change :)

**Comment by mpeiffer** [comment]
@hitblast  Sorry I didn't see this sooner! Thank you for fixing the linter issues.

**Comment by hitblast** [comment]
@mpeiffer No problem, It happens. Feel free to add more ideas to IgKnite which you might think be interesting!

**Pull request merged**
