### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by OjasMittal**
### Things changed:

- [ ] Start by listing your changes one by one.
- [x] Perfect changes must be ticked like this!

### CODE REVIEW

**Comment by OjasMittal** [comment]
Corrected some grammatical mistakes

**Review by hitblast — COMMENTED** [review]
How about no?

**Comment by OjasMittal** [comment]
Hello, as I am a beginner maybe my changes were not up to the mark. Kindly remove the spam label for my pull request, I will close it now.
Thank You.

**Comment by furtidev** [comment]
> Hello, as I am a beginner maybe my changes were not up to the mark. Kindly remove the spam label for my pull request, I will close it now. Thank You.

@OjasMittal Hey, sorry but the labels will stay as it is. We've received spam PRs before and we're fairly strict when it comes to these kinds of PRs. I've also looked into your recent activity just in case and all of them share the same pattern.

**Pull request closed without merging**
