### PR TITLE
Add /reset command for wiping text channels.

### PR DESCRIPTION
**Pull request by TheShonuff**
A basic implementation for creating a Text Channel and deleting the old Text Channel. I was able to successfully implement without **_@commants.has_role(LockRoles.admin)_** on my server as I wasn't able to successfully create the bot and add it to my server with the proper roles. I've added the **LockRoles** in for the submission.

### CODE REVIEW

**Comment by hitblast** [comment]
@TheShonuff Great work! Labelled it as `hacktoberfest-accepted` so that it counts for now. I have a few thoughts though:

The feature you've implemented looks neat. However, I've seen that you've replaced `'` with `"` and did some other stuff alongside the original requirement. I'd suggest removing the changes for now and keeping it for another PR as it might be a bit cluttered.

**Review by hitblast — CHANGES_REQUESTED** [review]
@TheShonuff Great work! Labelled it as `hacktoberfest-accepted` so that it counts for now. I have a few thoughts though:

The feature you've implemented looks neat. However, I've seen that you've replaced `'` with `"` and did some other stuff alongside the original requirement. I'd suggest removing the changes for now and keeping it for another PR as it might be a bit cluttered.

**Comment by TheShonuff** [comment]
Yeah I was kinda confused about those additional changes. When I was poking around I suspect vscode changed some items on save. I'll see about fixing those items after some sleep

**Comment by hitblast** [comment]
> Yeah I was kinda confused about those additional changes. When I was poking around I suspect vscode changed some items on save. I'll see about fixing those items after some sleep

Alright then, take your time :)

**Comment by TheShonuff** [comment]
I've reverted the affected files and made the appropriate changes to ONLY customization.py

**Review by hitblast — APPROVED** [review]
Banger PR! Will merge this evening. Thanks for your contribution :D

**Pull request merged**
