### PR TITLE
Implemented all **purge** related commands

### PR DESCRIPTION
**Pull request by furtidev**
### Log:

- [x] Added `/purge`
- [x] Added `/purgeone`
- [x] Added `/ripplepurge`

All replies made by these commands are ephemeral.

### CODE REVIEW

**Review by hitblast — CHANGES_REQUESTED** [review]
I guess you should have a look at the code and add the `required=True` flag to those options which are required. If not required, specify the default value within the option's description explicitly.

Example:
```python
options=[
    # non-required
    Option('amount', 'Specify the amount. Default is 1.', OptionType.integer),
    # required
    Option('member', 'Mention the server member', OptionType.user, required=True)
]
```

**Review by hitblast — CHANGES_REQUESTED** [review]
Line `103` and `110`: Aren't identifiers integers on Discord?

**Comment by furtidev** [comment]
Identifiers are not considered valid integers apparently (probably because they're too big). So that's the workaround. Couldn't find any documentation on the integer limit.

**Comment by hitblast** [comment]
Okay, LGTM then!

**Pull request merged**
