### PR TITLE
Resolved error handling for `/play` slash command.

### PR DESCRIPTION
**Pull request by prasoonmhwr**
- https://github.com/IgKniteDev/IgKnite/issues/50

### CODE REVIEW

**Comment by hitblast** [comment]
@prasoonmhwr Neat work! Could you please elaborate on your changes here? Meanwhile I'll label this as accepted.

**Review by hitblast — APPROVED** [review]
Approved. Awaiting merge.

**Comment by prasoonmhwr** [comment]
> @prasoonmhwr Neat work! Could you please elaborate on your changes here? Meanwhile I'll label this as accepted.

@hitblast Sure I actually while running play command the function checks for channel on voice of the inter.author but since the command was on a text channel , so it was unable to find the voice property on inter.author hence i applied a check on that and sending the message to switch to voice channel. Hope this explanation was helpful.


ONE REQUEST:- if its not to much to ask can you star my repo (https://github.com/prasoonmhwr) :)

**Comment by hitblast** [comment]
> > @prasoonmhwr Neat work! Could you please elaborate on your changes here? Meanwhile I'll label this as accepted.
> 
> @hitblast Sure I actually while running play command the function checks for channel on voice of the inter.author but since the command was on a text channel , so it was unable to find the voice property on inter.author hence i applied a check on that and sending the message to switch to voice channel. Hope this explanation was helpful.
> 
> ONE REQUEST:- if its not to much to ask can you star my repo (https://github.com/prasoonmhwr) :)

Pretty neat I'd say. Also, which repo? You tagged your profile link hehe.

**Comment by prasoonmhwr** [comment]
> > > @prasoonmhwr Neat work! Could you please elaborate on your changes here? Meanwhile I'll label this as accepted.
> > 
> > 
> > @hitblast Sure I actually while running play command the function checks for channel on voice of the inter.author but since the command was on a text channel , so it was unable to find the voice property on inter.author hence i applied a check on that and sending the message to switch to voice channel. Hope this explanation was helpful.
> > ONE REQUEST:- if its not to much to ask can you star my repo (https://github.com/prasoonmhwr) :)
> 
> Pretty neat I'd say. Also, which repo? You tagged your profile link hehe.

yes my profile repo only and also whichever repo is publicly available. :)

**Comment by hitblast** [comment]
> > > > @prasoonmhwr Neat work! Could you please elaborate on your changes here? Meanwhile I'll label this as accepted.
> > > 
> > > 
> > > @hitblast Sure I actually while running play command the function checks for channel on voice of the inter.author but since the command was on a text channel , so it was unable to find the voice property on inter.author hence i applied a check on that and sending the message to switch to voice channel. Hope this explanation was helpful.
> > > ONE REQUEST:- if its not to much to ask can you star my repo (https://github.com/prasoonmhwr) :)
> > 
> > 
> > Pretty neat I'd say. Also, which repo? You tagged your profile link hehe.
> 
> yes my profile repo only and also whichever repo is publicly available. :)

Alright then, merging and following you on GitHub. Also, if you're interested in some of my projects then feel free to follow as well :P

**Pull request merged**
