### PR TITLE
Added `/softban`, `/timeout`, `/snipe` and more!

### PR DESCRIPTION
**Pull request by hitblast**
### Things changed:

- [x] Added a basic `/softban` command which can be used to delete messages sent by a server member. Basically a faster alternative to `/purge` but it comes at the cost of a server member!
- [x] Added a new `/snipe` command which can be used to snipe / undo-delete messages within 25 seconds of their deletion period.
- [x] Added a new `/timeout` command which can be used to time out members inside a Discord server.
- [x] Removed unnecessary interaction actions from the `_purge` coroutine inside `cogs/Moderation.py`.
- [x] Updated the README.md file to be *partially* better, at least for now.

### CODE REVIEW

**Review by furtidev — CHANGES_REQUESTED** [review]
Do you think the README would look a little bit better if it was more compact?

**Comment by furtidev** [comment]
I think the main README should be as simple as possible. It should contain only necessary information, and if someone wants to learn more, they can always check out the wiki.

**Comment by hitblast** [comment]
> I think the main README should be as simple as possible. It should contain only necessary information, and if someone wants to learn more, they can always check out the wiki.

Alright, I'm merging the changes for now, and I'll file a separate PR with the requested changes for README.md. Thoughts? @furtidev

**Comment by furtidev** [comment]
Alright, works for me.

**Pull request merged**
