### PR TITLE
Fixed /now command not updating after audio is finished.

### PR DESCRIPTION
**Pull request by delivey**
Issue: #48 (only partly, will add volume and skip into another PR)

Let me know your thoughts on the code.
In line 696 raising an error when there is none might not be the most elegant solution, but it is the simplest & cleanest I found.

### CODE REVIEW

**Review by hitblast — CHANGES_REQUESTED** [review]
@delivey Looks pretty neat. How about you research a little bit more about line `696`?

**Comment by delivey** [comment]
I think I found a clean solution. Please take a look when you have time and let me know your thoughts.

**Review by hitblast — APPROVED** [review]
Approved! Could you please check the compatibility of this fix with other music commands which tend to use the `is_playing()` method? Thanks.

**Comment by delivey** [comment]
Seems like resume had some issues because it was using `inter.voice_state.is_playing` to check if the audio source existed and not if it was playing. Fixed now, cleaned up some code on other lines as well.

**Comment by hitblast** [comment]
Banger PR!

**Pull request merged**
