### PR TITLE
Tuning of `/queue` (Remove and Play buttons)

### PR DESCRIPTION
**Pull request by delivey**
This PR adds the functionality of Remove and Play buttons.

Issue: #70 

I know there are merge conflicts right now, fixing them after I create the PR.

Let me know if you have any questions / things I should change.

### CODE REVIEW

**Comment by hitblast** [comment]
@delivey Hey there! Seems like your PR is conflicting with `cogs/music.py`. Could you please have a look at it?

**Comment by delivey** [comment]
Merged.

**Comment by hitblast** [comment]
@delivey Also there are some tiny linting issues as well. I'm labelling this as `hacktoberfest-accepted` while you have a look at it ;)

**Review by hitblast — APPROVED** [review]
LGTM!

**Pull request merged**
